--- 
abstract: Lookup WHOIS data from norid.
author: Marcus Ramberg C<mramberg@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Whois-Norid
no_index: 
  directory: 
    - inc
    - t
requires: 
  Net::Whois::Raw: 0
version: 0.04
